### PR TITLE
Add specs as git submodules

### LINKED ISSUE #3: Spec documents missing?
The repository appears to be empty aside from the license and readme.

### PR DESCRIPTION
**Pull request by fabianhjr**
Closes: #3

### CODE REVIEW

**Comment by RichardLitt** [comment]
Looks fine to me. I no longer have merge rights for this repository, though.

**Comment by fabianhjr** [comment]
Oh sorry for the incorrect ping @RichardLitt :c

/cc @daviddias / @hacdias do anyone of you know who the current maintainer is?

**Comment by daviddias** [comment]
I don't think we want to add these as submodules. Any specific reason why you recommend it @fabianhjr ?

**Comment by daviddias** [comment]
Oh I see now, this repo was created with an intent but then lost its purpose given that the specs live by themselves on their own repo. Closing this and archiving this repo. Thanks for catching this @fabianhjr :)

**Pull request closed without merging**
